In [17]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.3
NumPy: 2.4.6

In [18]:
df=pd.read_csv('https://raw.githubusercontent.com/PALAK7890/Adaptive-Learning-Path-Recommendation-System/refs/heads/main/data/adaptive_learning_100k_realistic.csv')

In [19]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,last_topic_studied,time_available_hrs,learning_style,sessions_completed,streak_days,avg_session_min,preferred_difficulty,recommended_next_topic,recommended_difficulty,learning_sequence_step
0,GP,M,16,U,LE3,T,4,2,teacher,services,...,Machine Learning,7,Reading,25,11.226063,42.136846,Medium,Deep Learning,Medium,1
1,MS,M,17,U,GT3,T,2,3,services,health,...,Machine Learning,17,Video,42,7.240015,34.095945,Hard,Deep Learning,Easy,4
2,MS,F,15,U,LE3,T,0,3,teacher,services,...,Deep Learning,6,Video,20,0.000000,16.606751,Hard,NLP,Hard,2
3,MS,F,17,U,GT3,T,4,4,at_home,services,...,Python Basics,3,Video,44,19.774461,85.805891,Hard,NumPy,Medium,2
4,GP,F,16,R,LE3,T,2,3,other,teacher,...,Deep Learning,17,Practice,19,11.166520,36.772262,Easy,NLP,Hard,1

In [20]:
df.shape

(100000, 49)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 49 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   school                  100000 non-null  str
 1   sex                     100000 non-null  str
 2   age                     100000 non-null  int64
 3   address                 100000 non-null  str
 4   famsize                 100000 non-null  str
 5   Pstatus                 100000 non-null  str
 6   Medu                    100000 non-null  int64
 7   Fedu                    100000 non-null  int64
 8   Mjob                    100000 non-null  str
 9   Fjob                    100000 non-null  str
 10  reason                  100000 non-null  str
 11  guardian                100000 non-null  str
 12  traveltime              100000 non-null  int64
 13  studytime               100000 non-null  int64
 14  failures                100000 non-null  int64
 15  schoolsup               100000 non-null  str
 16  famsup                  100000 non-null  str
 17  paid                    100000 non-null  str
 18  activities              100000 non-null  str
 19  nursery                 100000 non-null  str
 20  higher                  100000 non-null  str
 21  internet                100000 non-null  str
 22  romantic                100000 non-null  str
 23  famrel                  100000 non-null  int64
 24  freetime                100000 non-null  int64
 25  goout                   100000 non-null  int64
 26  Dalc                    100000 non-null  int64
 27  Walc                    100000 non-null  int64
 28  health                  100000 non-null  int64
 29  absences                100000 non-null  int64
 30  G1                      98029 non-null   float64
 31  G2                      100000 non-null  float64
 32  G3                      100000 non-null  float64
 33  quiz_score_pct          91826 non-null   float64
 34  career_goal             97104 non-null   str
 35  math_skill              100000 non-null  str
 36  programming_skill       100000 non-null  str
 37  stats_skill             100000 non-null  str
 38  domain_skill            100000 non-null  str
 39  last_topic_studied      100000 non-null  str
 40  time_available_hrs      100000 non-null  int64
 41  learning_style          100000 non-null  str
 42  sessions_completed      100000 non-null  int64
 43  streak_days             99865 non-null   float64
 44  avg_session_min         95049 non-null   float64
 45  preferred_difficulty    100000 non-null  str
 46  recommended_next_topic  98821 non-null   str
 47  recommended_difficulty  100000 non-null  str
 48  learning_sequence_step  100000 non-null  int64
dtypes: float64(6), int64(16), str(27)
memory usage: 37.4 MB

In [22]:
df.isnull().sum()

school                       0
sex                          0
age                          0
address                      0
famsize                      0
Pstatus                      0
Medu                         0
Fedu                         0
Mjob                         0
Fjob                         0
reason                       0
guardian                     0
traveltime                   0
studytime                    0
failures                     0
schoolsup                    0
famsup                       0
paid                         0
activities                   0
nursery                      0
higher                       0
internet                     0
romantic                     0
famrel                       0
freetime                     0
goout                        0
Dalc                         0
Walc                         0
health                       0
absences                     0
G1                        1971
G2                           0
G3                           0
quiz_score_pct            8174
career_goal               2896
math_skill                   0
programming_skill            0
stats_skill                  0
domain_skill                 0
last_topic_studied           0
time_available_hrs           0
learning_style               0
sessions_completed           0
streak_days                135
avg_session_min           4951
preferred_difficulty         0
recommended_next_topic    1179
recommended_difficulty       0
learning_sequence_step       0
dtype: int64

In [23]:
num_cols = [
    'G1',
    'quiz_score_pct',
    'streak_days',
    'avg_session_min'
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [24]:
cat_cols = [
    'career_goal',
    'recommended_next_topic'
]

for col in cat_cols:
    df[col] = df[col].fillna('Unknown')

In [25]:
df.isnull().sum().sum()

np.int64(0)

In [26]:
df['recommended_difficulty'].value_counts(normalize=True)

recommended_difficulty
Medium    0.51537
Hard      0.27960
Easy      0.20503
Name: proportion, dtype: float64

In [27]:
df['learning_sequence_step'].value_counts(normalize=True)

learning_sequence_step
1    0.34625
2    0.28022
3    0.18282
4    0.11992
5    0.07079
Name: proportion, dtype: float64

In [28]:
df['recommended_next_topic'].value_counts()

recommended_next_topic
GenAI               12468
NumPy               11554
Deep Learning       11396
Pandas              10574
Statistics           8867
MLOps                8060
Computer Vision      7898
NLP                  7757
Probability          6980
Linear Algebra       6306
Machine Learning     6144
Unknown              1179
Python Basics         817
Name: count, dtype: int64

CHECKING THE SKEWNESS

In [31]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,absences,G1,G2,G3,quiz_score_pct,time_available_hrs,sessions_completed,streak_days,avg_session_min,learning_sequence_step
count,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,16.97338,2.474010,2.398500,1.970090,2.545470,0.334690,2.989000,3.000680,3.076090,2.99652,...,2.043312,13.359568,13.326322,13.243788,66.082213,15.524610,3.354889,2.169125,3.787264,2.288780
std,1.45709,1.234755,1.231322,1.076386,1.082508,0.677183,1.413364,1.413683,1.151883,1.41254,...,0.663811,3.225180,3.713836,3.913504,19.834678,8.652337,0.947488,1.363988,0.531660,1.249993
min,15.00000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.981641,1.000000
25%,16.00000,2.000000,2.000000,1.000000,2.000000,0.000000,2.000000,2.000000,2.000000,2.00000,...,1.609438,11.541905,10.908661,10.736833,53.989062,8.000000,2.708050,1.213394,3.475406,1.000000
50%,17.00000,3.000000,2.000000,2.000000,3.000000,0.000000,3.000000,3.000000,3.000000,3.00000,...,1.945910,13.780835,13.631727,13.592488,67.567285,15.000000,3.258097,2.478194,3.812982,2.000000
75%,18.00000,3.000000,3.000000,3.000000,3.000000,0.000000,4.000000,4.000000,4.000000,4.00000,...,2.197225,15.599840,16.028212,16.097338,80.094922,23.000000,3.850148,3.099053,4.122699,3.000000
max,22.00000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.00000,...,4.543295,20.000000,20.000000,20.000000,100.000000,30.000000,6.561031,5.535449,5.991465,5.000000

CORRECTING THE SKEWNESS

In [32]:

skew_cols = [
    "absences",
    "sessions_completed",
    "streak_days",
    "avg_session_min"
]

for col in skew_cols:
    df[col] = np.log1p(df[col])

In [33]:
cat_cols = df.select_dtypes(include='object').columns

print(cat_cols)
print()
print("Total categorical columns:", len(cat_cols))

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'career_goal',
       'math_skill', 'programming_skill', 'stats_skill', 'domain_skill',
       'last_topic_studied', 'learning_style', 'preferred_difficulty',
       'recommended_next_topic', 'recommended_difficulty'],
      dtype='str')

Total categorical columns: 27

/var/folders/ny/qt9pk8lx55q5bm060kfltck00000gp/T/ipykernel_43942/1545386740.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns

In [34]:
X = df.drop(
    columns=[
        "recommended_difficulty",
        "recommended_next_topic",
        "learning_sequence_step"
    ]
)

y_diff = df["recommended_difficulty"]

y_topic = df["recommended_next_topic"]

Encode Feature Columns

In [35]:
from sklearn.preprocessing import LabelEncoder

feature_encoders = {}

cat_cols = X.select_dtypes(include="object").columns

for col in cat_cols:
    le = LabelEncoder()

    X[col] = le.fit_transform(X[col])

    feature_encoders[col] = le

/var/folders/ny/qt9pk8lx55q5bm060kfltck00000gp/T/ipykernel_43942/1818377891.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include="object").columns

Encode Targets

In [37]:
difficulty_encoder = LabelEncoder()

y_diff = difficulty_encoder.fit_transform(y_diff)

topic_encoder = LabelEncoder()

y_topic = topic_encoder.fit_transform(y_topic)

SCALING THE FEATURES

In [39]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [41]:
X_train, X_test, y_diff_train, y_diff_test, y_topic_train, y_topic_test = train_test_split(
    X_scaled,
    y_diff,
    y_topic,
    test_size=0.2,
    random_state=42,
    stratify=y_diff
)

In [42]:
print(X.shape)

print(y_diff.shape)

print(y_topic.shape)

print(X_scaled.shape)

print(np.isnan(X_scaled).sum())

(100000, 46)
(100000,)
(100000,)
(100000, 46)
0

In [44]:
import torch
from torch.utils.data import Dataset

class AdaptiveLearningDataset(Dataset):

    def __init__(self, X, y_diff, y_topic):

        self.X = torch.tensor(X, dtype=torch.float32)

        self.y_diff = torch.tensor(
            y_diff,
            dtype=torch.long
        )

        self.y_topic = torch.tensor(
            y_topic,
            dtype=torch.long
        )

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):

        return (
            self.X[idx],
            self.y_diff[idx],
            self.y_topic[idx]
        )

Creating Dataset Objects

In [45]:
train_dataset=AdaptiveLearningDataset(X_train, y_diff_train,y_topic_train)
test_dataset=AdaptiveLearningDataset(X_test,y_diff_test,y_topic_test)