In [17]:
import pandas as pd
import matplotlib.pyplot as plt

In [18]:

df = pd.read_csv("../data/student_profiles.csv")

In [19]:
df.head()

,student_id,age,education_level,career_goal,experience_level,study_hours_per_week,learning_style,interest_ai,interest_data_science,interest_web_dev,...,projects_completed,quiz_attempts,quiz_avg_score,consistency_score,streak_days,target_completion_months,available_hours_weekly,recommended_next_topic,recommended_difficulty,learning_path_stage
0,STU00001,17,High School,Full Stack Developer,Beginner,76.31,Visual,46.05,75.81,55.28,...,2,11,35.25,82.32,9.0,18,13.9,SQL,Easy,2
1,STU00002,20,Bachelor,ML Engineer,Beginner,40.00,Reading/Writing,100.00,81.66,44.58,...,1,6,70.52,78.19,7.0,18,6.8,Deep Learning,Easy,2
2,STU00003,24,PhD,AI Engineer,Intermediate,6.04,Kinesthetic,63.01,62.06,61.07,...,6,8,35.40,70.38,10.0,9,8.2,Git,Medium,2
3,STU00004,29,High School,Backend Developer,Intermediate,16.51,Kinesthetic,62.79,51.71,49.12,...,5,5,27.63,38.29,NaN,9,12.0,SQL,Easy,3
4,STU00005,18,Bachelor,Software Engineer,Beginner,3.93,Auditory,53.82,56.61,30.49,...,2,3,46.08,61.56,7.0,6,10.0,Python,Easy,1

In [20]:
df.shape

(15000, 45)

In [21]:
df.isnull().sum()

student_id                     0
age                            0
education_level                0
career_goal                  450
experience_level               0
study_hours_per_week           0
learning_style                 0
interest_ai                    0
interest_data_science          0
interest_web_dev               0
interest_backend               0
interest_frontend              0
interest_mobile                0
interest_cloud                 0
interest_cybersecurity         0
python_score                   0
cpp_score                      0
java_score                     0
javascript_score               0
html_score                     0
css_score                      0
sql_score                      0
database_score                 0
statistics_score               0
probability_score              0
linear_algebra_score           0
calculus_score                 0
machine_learning_score         0
deep_learning_score            0
git_score                      0
linux_score                    0
docker_score                   0
cloud_score                  600
sessions_completed             0
avg_session_duration         750
projects_completed             0
quiz_attempts                  0
quiz_avg_score              1200
consistency_score              0
streak_days                  900
target_completion_months       0
available_hours_weekly         0
recommended_next_topic         0
recommended_difficulty         0
learning_path_stage            0
dtype: int64

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   student_id                15000 non-null  str
 1   age                       15000 non-null  int64
 2   education_level           15000 non-null  str
 3   career_goal               14550 non-null  str
 4   experience_level          15000 non-null  str
 5   study_hours_per_week      15000 non-null  float64
 6   learning_style            15000 non-null  str
 7   interest_ai               15000 non-null  float64
 8   interest_data_science     15000 non-null  float64
 9   interest_web_dev          15000 non-null  float64
 10  interest_backend          15000 non-null  float64
 11  interest_frontend         15000 non-null  float64
 12  interest_mobile           15000 non-null  float64
 13  interest_cloud            15000 non-null  float64
 14  interest_cybersecurity    15000 non-null  float64
 15  python_score              15000 non-null  float64
 16  cpp_score                 15000 non-null  float64
 17  java_score                15000 non-null  float64
 18  javascript_score          15000 non-null  float64
 19  html_score                15000 non-null  float64
 20  css_score                 15000 non-null  float64
 21  sql_score                 15000 non-null  float64
 22  database_score            15000 non-null  float64
 23  statistics_score          15000 non-null  float64
 24  probability_score         15000 non-null  float64
 25  linear_algebra_score      15000 non-null  float64
 26  calculus_score            15000 non-null  float64
 27  machine_learning_score    15000 non-null  float64
 28  deep_learning_score       15000 non-null  float64
 29  git_score                 15000 non-null  float64
 30  linux_score               15000 non-null  float64
 31  docker_score              15000 non-null  float64
 32  cloud_score               14400 non-null  float64
 33  sessions_completed        15000 non-null  int64
 34  avg_session_duration      14250 non-null  float64
 35  projects_completed        15000 non-null  int64
 36  quiz_attempts             15000 non-null  int64
 37  quiz_avg_score            13800 non-null  float64
 38  consistency_score         15000 non-null  float64
 39  streak_days               14100 non-null  float64
 40  target_completion_months  15000 non-null  int64
 41  available_hours_weekly    15000 non-null  float64
 42  recommended_next_topic    15000 non-null  str
 43  recommended_difficulty    15000 non-null  str
 44  learning_path_stage       15000 non-null  int64
dtypes: float64(32), int64(6), str(7)
memory usage: 5.1 MB

In [23]:
df.isnull().sum()

student_id                     0
age                            0
education_level                0
career_goal                  450
experience_level               0
study_hours_per_week           0
learning_style                 0
interest_ai                    0
interest_data_science          0
interest_web_dev               0
interest_backend               0
interest_frontend              0
interest_mobile                0
interest_cloud                 0
interest_cybersecurity         0
python_score                   0
cpp_score                      0
java_score                     0
javascript_score               0
html_score                     0
css_score                      0
sql_score                      0
database_score                 0
statistics_score               0
probability_score              0
linear_algebra_score           0
calculus_score                 0
machine_learning_score         0
deep_learning_score            0
git_score                      0
linux_score                    0
docker_score                   0
cloud_score                  600
sessions_completed             0
avg_session_duration         750
projects_completed             0
quiz_attempts                  0
quiz_avg_score              1200
consistency_score              0
streak_days                  900
target_completion_months       0
available_hours_weekly         0
recommended_next_topic         0
recommended_difficulty         0
learning_path_stage            0
dtype: int64

In [24]:
num_cols = [
    'avg_session_duration',
    'cloud_score',
    'quiz_avg_score',
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())
df["streak_days"] = df["streak_days"].fillna(0)

In [25]:
cat_cols = [
    'career_goal',
    'recommended_next_topic'
]

for col in cat_cols:
    df[col] = df[col].fillna('Unknown')

In [ ]:
df.isnull().sum().sum()

In [27]:
df.describe()

,age,study_hours_per_week,interest_ai,interest_data_science,interest_web_dev,interest_backend,interest_frontend,interest_mobile,interest_cloud,interest_cybersecurity,...,sessions_completed,avg_session_duration,projects_completed,quiz_attempts,quiz_avg_score,consistency_score,streak_days,target_completion_months,available_hours_weekly,learning_path_stage
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,...,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,25.423933,15.136844,63.311347,59.454951,54.388313,49.725942,47.887835,40.087695,45.056563,36.475820,...,27.636600,48.001950,3.607200,7.484400,56.689481,50.732216,7.720333,7.973533,14.104000,2.082867
std,5.594929,10.901755,20.765762,20.400399,20.082377,19.636035,19.528303,17.600332,18.683154,18.496807,...,49.428148,33.849194,2.999696,4.357058,19.571663,19.907389,6.474018,5.068374,7.841778,1.227939
min,17.000000,1.230000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.700000,1.000000
25%,22.000000,8.090000,48.450000,45.227500,40.460000,36.130000,34.510000,28.120000,32.185000,23.590000,...,9.000000,29.820000,1.000000,4.000000,44.527500,37.150000,4.000000,6.000000,8.400000,1.000000
50%,25.000000,12.190000,63.150000,59.120000,54.065000,49.280000,47.400000,40.120000,44.640000,36.120000,...,17.000000,41.080000,3.000000,7.000000,56.795000,50.720000,7.000000,6.000000,12.200000,2.000000
75%,28.000000,18.562500,78.692500,73.732500,68.052500,62.627500,60.580000,52.010000,57.382500,48.340000,...,30.000000,56.060000,5.000000,10.000000,69.320000,64.320000,10.000000,9.000000,17.700000,3.000000
max,44.000000,79.700000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,594.000000,359.600000,26.000000,34.000000,100.000000,100.000000,70.000000,24.000000,40.000000,5.000000

In [ ]:
df.to_csv(
    "student_profiles_clean.csv",
    index=False
)